Imports

In [21]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go

from datetime import datetime
from datetime import date

%matplotlib inline

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 140)

DATA_PATH = "Data/"  
clients = pd.read_csv(DATA_PATH+"clients_a_contacter.csv")

Imports

Première visualisation des données

In [22]:
display(clients.head(10))

,id_client,genre,age,permis_conduire,code_regional,ancien_assure,age_vehicule,vehicule_endommage,prime_annuelle,canal_communication,anciennete
0,381110,male,25,1,11.0,1,< 1 an,no,35786.0,152.0,53
1,381111,male,40,1,28.0,0,1-2 an,oui,33762.0,7.0,111
2,381112,male,47,1,28.0,0,1-2 an,oui,40050.0,124.0,199
3,381113,male,24,1,27.0,1,< 1 an,oui,37356.0,152.0,187
4,381114,male,27,1,28.0,1,< 1 an,no,59097.0,152.0,297
5,381115,male,22,1,30.0,1,< 1 an,no,40207.0,152.0,266
6,381116,femelle,51,1,37.0,1,1-2 an,no,40118.0,26.0,107
7,381117,male,25,1,41.0,1,< 1 an,no,23375.0,152.0,232
8,381118,male,42,1,41.0,0,1-2 an,oui,2630.0,26.0,277
9,381119,femelle,37,1,12.0,1,1-2 an,no,27124.0,124.0,133

Résumé du jeu de données et typologie des variables : Commencez par obtenir une vue d’ensemble
du dataset (dimensions, types de variables, statistiques descriptives). Il s’agit notamment d’identifier
les variables quantitatives et catégorielles, ainsi que de détecter d’éventuels problèmes tels que des
valeurs manquantes ou des valeurs aberrantes

In [ ]:
def clients_shape():
    return clients.shape
def clients_type():
    return clients.info()
def clients_valeur_manquantes():
    return clients.notna()
def clients_duplicated_values():
    lignes, _ = clients[clients.duplicated()].shape
    return lignes

In [32]:
display(clients.notna())

,id_client,genre,age,permis_conduire,code_regional,ancien_assure,age_vehicule,vehicule_endommage,prime_annuelle,canal_communication,anciennete
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
127032,True,True,True,True,True,True,True,True,True,True,True
127033,True,True,True,True,True,True,True,True,True,True,True
127034,True,True,True,True,True,True,True,True,True,True,True
127035,True,True,True,True,True,True,True,True,True,True,True
127036,True,True,True,True,True,True,True,True,True,True,True

0